In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
from scripts import dataset
from scripts import tt

In [22]:
original_data = pd.read_json("../kb/KBR.json")

original_data = original_data[original_data.dimension != 'consistency']

dimensions = original_data.dimension.unique()
models = original_data.model.unique()
datasets = original_data.name.unique()

datasets_fd = ["BachChoralHarmony", "bank", "cancer", "mushrooms", "soybean"]

data_copy = dataset.get_dataset()

data_copy = data_copy[data_copy.dimension != 'consistency']

In [23]:
### evaluation del ranking

In [24]:
tt.test_rankings()

Done!


In [25]:
pred_dim = []
pred_score = []

In [26]:
tt.evaluate_rankings()

Done!


In [19]:
rankings = pd.read_csv("../results/results_ranking_evaluation.csv")
rankings

dataset         model     dimension      real      pred
0                   abalone_0  DecisionTree  completeness  0.765890  0.926588
1                   abalone_1  DecisionTree  completeness  0.805338  0.898511
2                   abalone_2  DecisionTree  completeness  0.840417  0.902173
3                   abalone_3  DecisionTree  completeness  0.901727  0.906498
4                   abalone_4  DecisionTree  completeness  0.990326  0.911736
...                       ...           ...           ...       ...       ...
1645  wall-robot-navigation_0           SVC      accuracy  0.352863  0.618745
1646  wall-robot-navigation_1           SVC      accuracy  0.371848  0.638558
1647  wall-robot-navigation_2           SVC      accuracy  0.350599  0.574945
1648  wall-robot-navigation_3           SVC      accuracy  0.322374  0.602149
1649  wall-robot-navigation_4           SVC      accuracy  0.441342  0.682134

[1650 rows x 5 columns]

In [20]:
rankings = pd.read_csv("../results/results_ranking_evaluation_total.csv")
rankings


dataset               model  ranking_eval  \
0                  abalone_0        DecisionTree           0.0   
1                  abalone_0  LogisticRegression           1.0   
2                  abalone_0                 KNN           1.0   
3                  abalone_0        RandomForest           1.0   
4                  abalone_0            AdaBoost           0.0   
..                       ...                 ...           ...   
745  wall-robot-navigation_4  LogisticRegression           1.0   
746  wall-robot-navigation_4                 KNN           1.0   
747  wall-robot-navigation_4        RandomForest           0.0   
748  wall-robot-navigation_4            AdaBoost           0.0   
749  wall-robot-navigation_4                 SVC           1.0   

                    ranking_real                 ranking_pred  \
0    ['completeness' 'accuracy']  ['accuracy' 'completeness']   
1    ['accuracy' 'completeness']  ['accuracy' 'completeness']   
2    ['accuracy' 'completeness']  ['accuracy' 'completeness']   
3    ['accuracy' 'completeness']  ['accuracy' 'completeness']   
4    ['completeness' 'accuracy']  ['accuracy' 'completeness']   
..                           ...                          ...   
745  ['accuracy' 'completeness']  ['accuracy' 'completeness']   
746  ['accuracy' 'completeness']  ['accuracy' 'completeness']   
747  ['accuracy' 'completeness']  ['completeness' 'accuracy']   
748  ['completeness' 'accuracy']  ['accuracy' 'completeness']   
749  ['accuracy' 'completeness']  ['accuracy' 'completeness']   

                  value_real               value_pred  
0    [0.76589018 0.81065113]  [0.71757723 0.92658765]  
1    [0.59913287 0.82957761]  [0.62398985 0.93969753]  
2    [0.65651218 0.85711745]  [0.59185609 0.93377876]  
3    [0.78598963 0.87738755]  [0.76913906 0.94596356]  
4    [0.71600238 0.84769537]  [0.84821748 0.86591785]  
..                       ...                      ...  
745  [0.51867583 0.86567347]  [0.73001117 0.95184968]  
746  [0.85376707 0.93745886]  [0.83682697 0.9663684 ]  
747  [0.946756   0.96250289]  [0.94154472 0.96259183]  
748  [0.99231298 1.15981565]  [0.8917544  0.95523212]  
749  [0.4413419  0.63336062]  [0.68213426 0.95163265]  

[750 rows x 7 columns]

In [21]:
rankings.describe()


ranking_eval
count    750.000000
mean       0.743111
std        0.420255
min        0.000000
25%        0.333333
50%        1.000000
75%        1.000000
max        1.000000

In [10]:
rankings.ranking_eval.value_counts()


ranking_eval
1.000000    541
0.000000    160
0.333333     49
Name: count, dtype: int64

In [11]:
### nel 75% dei casi abbiamo il ranking corretto
### in particolare nel 72% dei casi abbiamo il ranking totalmente corretto
### nel 6.5% dei casi abbiamo solo una dimensione su 3 corretta (perchè la altre due sono scambiate)

In [12]:
wrong = rankings[rankings.ranking_eval < 1]


In [13]:
wrong.dataset.unique()


array(['abalone_0', 'abalone_1', 'abalone_2', 'abalone_3', 'abalone_4',
       'BachChoralHarmony_0', 'BachChoralHarmony_2',
       'BachChoralHarmony_4', 'bank_0', 'bank_1', 'bank_2', 'bank_3',
       'bank_4', 'cancer_0', 'cancer_1', 'cancer_2', 'cancer_3',
       'cancer_4', 'car_0', 'car_1', 'car_2', 'car_3', 'car_4',
       'default of credit card clients_0',
       'default of credit card clients_1',
       'default of credit card clients_2',
       'default of credit card clients_3',
       'default of credit card clients_4', 'drug_0', 'drug_2', 'drug_3',
       'drug_4', 'electricity-normalized_1', 'electricity-normalized_3',
       'electricity-normalized_4', 'fried_0', 'fried_1', 'fried_3',
       'frogs_1', 'frogs_2', 'frogs_3', 'frogs_4', 'german_3', 'german_4',
       'house_0', 'house_1', 'house_2', 'house_3', 'house_4', 'iris_3',
       'iris_4', 'letter_0', 'letter_2', 'letter_3', 'letter_4',
       'mushrooms_0', 'mushrooms_1', 'mushrooms_2', 'mushrooms_3',
       'mus

In [14]:
wrong.model.unique()


array(['DecisionTree', 'AdaBoost', 'RandomForest', 'LogisticRegression',
       'SVC', 'KNN'], dtype=object)

In [15]:
wrong.ranking_real.value_counts()


ranking_real
['completeness' 'accuracy']                  113
['accuracy' 'completeness']                   42
['completeness' 'accuracy' 'consistency']     25
['accuracy' 'consistency' 'completeness']     16
['accuracy' 'completeness' 'consistency']      8
['consistency' 'completeness' 'accuracy']      3
['completeness' 'consistency' 'accuracy']      2
Name: count, dtype: int64

In [16]:
wrong.ranking_pred.value_counts()


ranking_pred
['accuracy' 'completeness']                  113
['accuracy' 'completeness' 'consistency']     43
['completeness' 'accuracy']                   42
['completeness' 'accuracy' 'consistency']     11
Name: count, dtype: int64

In [17]:
wrong


dataset         model  ranking_eval  \
0                  abalone_0  DecisionTree           0.0   
4                  abalone_0      AdaBoost           0.0   
10                 abalone_1      AdaBoost           0.0   
12                 abalone_2  DecisionTree           0.0   
16                 abalone_2      AdaBoost           0.0   
..                       ...           ...           ...   
736  wall-robot-navigation_2      AdaBoost           0.0   
741  wall-robot-navigation_3  RandomForest           0.0   
742  wall-robot-navigation_3      AdaBoost           0.0   
747  wall-robot-navigation_4  RandomForest           0.0   
748  wall-robot-navigation_4      AdaBoost           0.0   

                    ranking_real                 ranking_pred  \
0    ['completeness' 'accuracy']  ['accuracy' 'completeness']   
4    ['completeness' 'accuracy']  ['accuracy' 'completeness']   
10   ['completeness' 'accuracy']  ['accuracy' 'completeness']   
12   ['completeness' 'accuracy']  ['accuracy' 'completeness']   
16   ['accuracy' 'completeness']  ['completeness' 'accuracy']   
..                           ...                          ...   
736  ['completeness' 'accuracy']  ['accuracy' 'completeness']   
741  ['accuracy' 'completeness']  ['completeness' 'accuracy']   
742  ['completeness' 'accuracy']  ['accuracy' 'completeness']   
747  ['accuracy' 'completeness']  ['completeness' 'accuracy']   
748  ['completeness' 'accuracy']  ['accuracy' 'completeness']   

                  value_real               value_pred  
0    [0.76589018 0.81065113]  [0.71757723 0.92658765]  
4    [0.71600238 0.84769537]  [0.84821748 0.86591785]  
10   [0.71686303 0.86271963]  [0.8302403  0.95979445]  
12   [0.84041742 0.88314255]  [0.82790576 0.90217272]  
16   [0.71694682 0.84018426]  [0.87604969 0.89995697]  
..                       ...                      ...  
736  [1.01044103 1.01609996]  [0.83342483 0.88557725]  
741  [0.91722645 0.92891672]  [0.94145208 0.94855794]  
742  [1.07204625 1.08338581]  [0.85400908 0.92638422]  
747  [0.946756   0.96250289]  [0.94154472 0.96259183]  
748  [0.99231298 1.15981565]  [0.8917544  0.95523212]  

[209 rows x 7 columns]

In [18]:
### controllo la differenza nel ranking real

In [19]:
variance_impact = []
wrong = wrong.reset_index(drop=True)
for i in range(0,len(wrong)):
    s = wrong.loc[i].value_real
    print(s)
    s = s.replace(".        ]",".0]")
    s = s.replace("   "," ")
    s = s.replace("  "," ")
    s = s.replace(" ]","]")
    s = s.replace("\'","")
    s = s.replace("[","")
    s = s.replace("]","")
    s = s.split(" ")
    s = np.array(s)
    s = s.astype(float)

    variance_impact.append(s[0] - s[1])

[0.76589018 0.81065113]
[0.71600238 0.84769537]
[0.71686303 0.86271963]
[0.84041742 0.88314255]
[0.71694682 0.84018426]
[0.90172666 0.92078931]
[0.85665293 0.86250357]
[0.94908976 0.99032578]
[0.85922217 0.93183873]
[0.82241864 0.98525708]
[0.67975679 0.71160472 0.86543824]
[0.58549451 0.60313034 0.85078554]
[0.7025672  0.73931941 0.80146686]
[0.62729765 0.73352923 1.15732647]
[0.86920717 0.87890568 0.89259998]
[0.84511747 0.87641012 0.89426608]
[0.76734859 0.84179307 1.46525735]
[0.96857095 0.97367834 0.97787163]
[0.95528588 0.98282615 0.99561069]
[0.94851755 0.95680561 0.96855374]
[0.91087031 0.94996614 0.95396135]
[0.97594389 0.98336509 0.98821823]
[0.95084968 0.97082716 0.99240604]
[0.95387938 0.96847246 0.97186355]
[0.96699141 0.97696467 0.99758777]
[0.91248049 0.92860139 0.95378796]
[0.97945222 0.98804307 0.99044527]
[0.94127887 0.96335318 0.98341376]
[0.9419718  0.96507909 0.97279905]
[0.93278887 0.97330282 0.97403325]
[0.99273509 0.99314227 1.00183535]
[0.93621621 0.96522265 0.

In [20]:
variance_impact = pd.DataFrame(variance_impact)


In [21]:
variance_impact = abs(variance_impact)


In [22]:
variance_impact.describe()


0
count  209.000000
mean     0.059677
std      0.116403
min      0.000005
25%      0.009699
50%      0.027803
75%      0.061699
max      1.168874

In [23]:
variance_impact

0
0    0.044761
1    0.131693
2    0.145857
3    0.042725
4    0.123237
..        ...
204  0.005659
205  0.011690
206  0.011340
207  0.015747
208  0.167503

[209 rows x 1 columns]

In [24]:
### succede quando i ranking sono molto vicini tra di loro --> il 75% percentile è 0.06
### in media se ho un threshold di similarità di impatto che si aggira intorno al 5% allora il nostro ranking non è più affidabile!
